### PR TITLE
add villes.json ==> all DRC's cities

### PR DESCRIPTION
**Pull request by ljoboy**
I add a files containing alll cities with a reference to the id of the related province

### CODE REVIEW

**Review by bernard-ng — COMMENTED** [review]
Nice work @ljoboy  but what is province_id and where does it come from ?

**Comment by ljoboy** [comment]
In administratives each provinces got an id so province_id it's a reference to the referred province

**Comment by bernard-ng** [comment]
rename the file to **cities** or **towns** and I will merge your work

**Comment by ljoboy** [comment]
Okay

**Comment by ljoboy** [comment]
Done

**Review by bernard-ng — APPROVED** [review]

**Pull request merged**
